name: Auto Merge After Successful Build

on:
  workflow_run:
    workflows: ["Full Stack Auto PR + Build"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Wait for GitHub to register status
        run: sleep 10

      - name: Auto merge pull requests with label auto-merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: auto-merge
          MERGE_COMMIT_MESSAGE: "🎉 Auto merged after successful frontend & backend checks"
