name: Auto Merge After Successful Build

on:
  pull_request_target:
    types: [opened, labeled, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:

      - name: Wait for PR to be ready
        run: sleep 60  # Give GitHub time to register PR and label


      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: auto-merge
          MERGE_COMMIT_MESSAGE: "🎉 Auto merged after successful build"

