name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - name: Auto merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: auto-merge
          MERGE_COMMIT_MESSAGE: "🎉 Auto merged from ${{ github.head_ref }} after successful frontend & backend checks"
