name: Full Stack Auto PR + Build + Auto Merge

# Trigger on any push to a feature branch
on:
  push:
    branches:
      - "feature/*"

permissions:
  contents: write
  pull-requests: write

jobs:
  # Step 1: Create or update Pull Request
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get default branch dynamically
        id: default-branch
        run: |
          echo "DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)" >> $GITHUB_ENV

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: ${{ env.DEFAULT_BRANCH }}
          title: "🚀 Auto PR from ${{ github.ref_name }}"
          body: "Automated PR from `${{ github.ref_name }}`. Will auto-merge if all checks pass."
          reviewers: Akash-Adak
          labels: auto-merge, fullstack, feature
          auto-merge: true         # ✅ Automatically merge when all checks pass
          merge-method: squash

  # Step 2: Frontend build
  frontend:
    runs-on: ubuntu-latest
    needs: create-pr
    defaults:
      run:
        working-directory: Frontend/SIH/Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist  # Adjust if your build folder is different

  # Step 3: Backend build and tests
  backend:
    runs-on: ubuntu-latest
    needs: create-pr
    defaults:
      run:
        working-directory: Backend/SIH
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run Tests
        run: mvn test

